name: login_page
description: "A Flutter project for managing pantry inventory and finding recipes."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  csv: ^5.0.0  # CSV parsing package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_bg.png
    - assets/recipe/recipes.csv 
      # Include your CSV file